services:
  chatexo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatexo-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - .:/app

  luminaire-frontend:
    build:
      context: ../luminaire-global-coorp
      dockerfile: Dockerfile
    container_name: luminaire-frontend
    restart: unless-stopped
    ports:
      - "3000:80"

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP
      - '443:443'   # HTTPS
      - '81:81'     # Admin UI
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

  redis:
    image: redis:7-alpine
    container_name: chatexo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: chatexo-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  logs:
  npm-data:
  npm-letsencrypt:
  redis_data: